### ISSUE TITLE
full force duel

### ISSUE THREAD

**Issue by Razish** [Razish/japp#159]

**Comment by ineedblood** [comment]
any advances?

**Comment by ensiform** [comment]
Not that I'm aware of.

**Comment by Razish** [comment]
I'm doing full-time shift work, I've barely had time to work on my engine, JA++ or OpenJK.
This is one of the things I'd like to have done sooner rather than later at the moment.

**Comment by miguelsotobaez** [comment]
It would be great if the team done the full force duel feature. This is the only thing that i dont use your mod, i know its a great mod, but i still use the old version because this one dont have this feature. Hope the team have some time to work in it. I would help you but i dont understand to much how a quake based game works, im a front-end web developer only.

**Comment by ensiform** [comment]
Technically JA++ isn't a newer version of JA+.  It just aims to have some of the features where appropriate since the source to JA+ isn't available.
