### ISSUE TITLE
amsleep stops working

### ISSUE THREAD

**Issue by Razish** [Razish/japp#254]
> Amsleep suddenly stopped working entirely.  When it was executed, a player would flop down, then flop back up again and move around freely.  I believe <xxx> said that you could get out of it intentionally by arming and disarming yourself somehow, but not all of the players who got slept could have done that instantly, so it seems to have been completely disabled.

**Comment by Razish** [comment]
See 60a4c4e9fd8e957b72f47804963cf6b2239f6ddd and efac10777ecd3dfbad96cbe821fd2a8478e8931f

**Comment by Morabis** [comment]
I saw an issue with amsleep. If you sleep someone then you slap them while slept they can get up and move around freely also they are able to flipkick players but can't harm them with lightsaber. If they fall into a pit in this state they don't die but stuck there and can't do anything until they are awaken and die due to the pit dmg.

**Comment by EpicLoyd** [comment]
Probably fixed in ^, but i leave it open...

**Comment by Razish** [comment]
Might be better to put a check in BG_Knockdownable or such.

**Comment by Razish** [comment]
Have not had any reports since those commits, closing for now.
