### ISSUE TITLE
Undefined plugin

### ISSUE THREAD

**Issue by Paullik74** [Razish/japp#276]
Hello,
when I start game without "+set fs_game japlus", and then join to my server from server browser (JA+ 2.3 beta1 + plugin 1.4 build 4) I've got a message about undefinde plugin version.

![shot0000](https://cloud.githubusercontent.com/assets/10046079/5606727/96ce1704-943c-11e4-9cde-4871d188fec1.jpg)

**Comment by Razish** [comment]
Does launching with `+set fs_game "japlus"` result in the same issue?
What files do you have in GameData/japlus?

**Comment by Paullik74** [comment]
When launch with +set fs_game "japlus" everything's fine.
In GameData/japlus:

![image](https://cloud.githubusercontent.com/assets/10046079/5608261/1c60e068-947e-11e4-975a-396f46d55705.png)

**Comment by Razish** [comment]
There is not much that can be done for JA+ servers, the version sniffing is questionable to begin with, and is also not reliable, particularly if you set the associated userinfo field (`cjp_client`) after connecting.
It's best for that field to be set prior to connecting, which is why `+set fs_game "japlus"` is necessary.
