### ISSUE TITLE
Add: Don't end match if players are dueling in FFA

### ISSUE THREAD

**Issue by Razish** [Razish/japp#393]
optional

**Comment by jared-lovin** [comment]
In the process of implementing this, I ran across a few potential issues:

- Say client A and B are dueling and time limit reached. The code prevents intermission from taking place and they are still dueling. Now, during this time while A and B are dueling, clients C and D decide to duel. Should we also wait for C and D to finish, even though the time limit has passed?

- Client A and B are dueling and intermission isn't going to place because of so. Client B decides to go afk during the duel. Do we wait on B (imo no) or add a timeout?

- Do we care about the dueling gametypes (DUEL, POWERDUEL) or just ffa/tffa?

**Comment by Razish** [comment]
1) Yeah, we can wait.
2) A timeout feature is a good idea. This can be added later.
3) Lesser priority, can be added later

**Comment by ensiform** [comment]
I think new duels shouldn't be allowed to start in over time.
